# Generated by Django 3.0.2 on 2020-01-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
    ]
