# Generated by Django 3.0.2 on 2020-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20200122_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='alink',
            field=models.URLField(default='A website you wish to save.', max_length=130),
        ),
    ]
