# Generated by Django 3.0.2 on 2020-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.CharField(default='unknown user', max_length=50),
            preserve_default=False,
        ),
    ]
