# Generated by Django 3.0.2 on 2020-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20200118_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alink', models.CharField(default='A website you wish to save.', max_length=100)),
                ('nickname', models.CharField(default='An easy to remember nickname for your link.', max_length=40)),
                ('user', models.CharField(default='unknown user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Your todo list item here>', max_length=50)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.CharField(default='unknown user', max_length=50)),
            ],
        ),
    ]
