# Generated by Django 3.0.2 on 2020-01-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_bookmarks_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
