# Generated by Django 3.0.2 on 2020-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20200121_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Your goal here>', max_length=40)),
                ('user_id', models.CharField(default='unknown user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoalThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Your goal here>', max_length=40)),
                ('user_id', models.CharField(default='unknown user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Your goal here>', max_length=40)),
                ('user_id', models.CharField(default='unknown user', max_length=50)),
            ],
        ),
    ]
