# Generated by Django 3.0.2 on 2020-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeckoOneHome', '0002_auto_20200114_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.CharField(default='https://EXAMPLE/THisAWesomeBookmarkIfound/', max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='goal_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='goals',
            field=models.CharField(default='EXAMPLE: Create a chatbot using JavaScript', max_length=40),
        ),
        migrations.AddField(
            model_name='myuser',
            name='todo',
            field=models.CharField(default='EXAMPLE: Get a puppy.', max_length=40),
        ),
        migrations.AddField(
            model_name='myuser',
            name='todo_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='email address'), max_length=20),
        ),
    ]
