# Generated by Django 3.0.2 on 2020-01-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeckoOneHome', '0006_myuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
